name: outfitly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2  # Compatible with image_picker_web ^4.0.0
  image_picker_web: ^4.0.0  # Updated to the latest version
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.3.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - web/assets/icons/
    - web/assets/icons/default_avatar.png

flutter_native_splash:
  color: "#7206BF"
  color_dark: "#4C65D4"
  # background_image: "web/assets/icons/Icon-512.png" # (valfritt, om du har en bild)
  image: web/assets/icons/hanger-white.png  # Ersätt med rätt sökväg till din logotyp
  # branding: web/assets/icons/branding.png # (valfritt: t.ex. "Powered by Outfitly")
  branding_mode: bottom

  android_12:
    image: web/assets/icons/hanger-white.png
    icon_background_color: "#3c0563"
    icon_background_color_dark: "#4C65D4"

  web: true
