// lib/constants/wardrobe_constants.dart
const List<String> wardrobeCategories = [
  "Dresses",
  "Tops & T-Shirts",
  "Polos",
  "Jeans",
  "Pants",
  "Shorts",
  "Linen Layers",
  "Swimwear & Beachwear",
  "Shirts & Blouses",
  "Basics",
  "Skirts",
  "Heels",
  "Shoes",
  "Boots",
  "Sneakers",
  "Cardigans & Sweaters",

  "Blazers & Vests",
  "Jackets & Coats",
  "Outerwear",
  "Jumpsuits & Overalls",
  "Lingerie",
  "Loungewear",
  "Nightwear",
  "Socks & Tights",
  "Maternity Wear",
  "Hoodies & Sweatshirts",
  "Accessories",
  "Bags",
  "Headwear",
  "Jewelry",
  "Sunglasses",
  "Activewear",
  "Makeup",
  "Other",
];

const List<String> wardrobeColors = [
  "Black",
  "White",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Pink",
  "Purple",
  "Orange",
  "Gray",
  "Brown",
  "Beige",
  "Navy",
  "Teal",
  "Gold",
  "Silver",
  "Multicolor",
  "Other",
];

// Not used in the current implementation
const List<String> wardrobeBrands = [
  "Other",
  "& Other Stories",
  "Abercrombie & Fitch",
  "Acne Studios",
  "Adidas",
  "Amisu",
  "Arket",
  "ASOS",
  "Balenciaga",
  "Balmain",
  "Bershka",
  "Bikbok",
  "Birkenstock",
  "Boohoo",
  "Boozt",
  "Burberry",
  "C&A",
  "Calvin Klein",
  "Calzedonia",
  "Carin Wester",
  "Celine",
  "Chanel",
  "Cider",
  "Clarks",
  "Converse",
  "COS",
  "COQUETTE",
  "Crocs",
  "Dazy",
  "Dior",
  "Dolce & Gabbana",
  "Dr. Martens",
  "ECCO",
  "Fendi",
  "Filippa K",
  "Forever 21",
  "Ganni",
  "George",
  "Givenchy",
  "Gina Tricot",
  "Gucci",
  "H&M",
  "Headwear",
  "Hollister",
  "Hugo Boss",
  "House",
  "Indiska",
  "Jack & Jones",
  "Jewelry",
  "Kappahl",
  "Karl Lagerfeld",
  "Lager 157",
  "Levi's",
  "Lindex",
  "Louis Vuitton",
  "Mango",
  "Marks & Spencer",
  "Massimo Dutti",
  "Merrell",
  "Michael Kors",
  "Misguided",
  "Moncler",
  "Monki",
  "NA-KD",
  "Nelly",
  "New Balance",
  "New Collection",
  "New Look",
  "Nike",
  "Off-White",
  "ONLY",
  "Patagonia",
  "Pieces",
  "Polos",
  "Prada",
  "PrettyLittleThing",
  "Primark",
  "Pull & Bear",
  "Puma",
  "Reebok",
  "Reserved",
  "River Island",
  "Saint Laurent",
  "Salomon",
  "Samsoe & Samsoe",
  "Selected",
  "Shein",
  "Sinsay",
  "Skechers",
  "Soyaconcept",
  "Stone Island",
  "Stradivarius",
  "Superdry",
  "Superdry",
  "Tamaris",
  "Temu",
  "The North Face",
  "Timberland",
  "Tommy Hilfiger",
  "Topman",
  "Topshop",
  "UGG",
  "Under Armour",
  "Uniqlo",
  "Unknown",
  "Urban Outfitters",
  "Vagabond",
  "Vans",
  "Vero Moda",
  "Versace",
  "Vila",
  "Vintage",
  "Weekday",
  "Zalando",
  "Zara",
];

const List<String> wardrobeSizes = [
  // International clothing sizes
  'XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL',
  // Pants (EU sizes)
  'EU28', 'EU29', 'EU30', 'EU31', 'EU32', 'EU33', 'EU34', 'EU35',
  'EU36', 'EU37', 'EU38', 'EU39', 'EU40', 'EU41', 'EU42', 'EU43',
  'EU44', 'EU45', 'EU46',
  // Bras (simplified range)
  '70K', '70L', '70M', '75A', '75B', '75C', '75D', '75E', '75F',
  // Shoes (EU sizes)
  'EU33', 'EU34', 'EU35', 'EU36', 'EU37', 'EU38', 'EU39', 'EU40',
  'EU41', 'EU42', 'EU43', 'EU44', 'EU45', 'EU46', 'EU47', 'EU48',
  // Other
  'Other', 'Unknown',
];
