// lib/constants/wardrobe_constants.dart
const List<String> wardrobeCategories = [
  "Dresses",
  "Tops & T-Shirts",
  "Polos",
  "Jeans",
  "Pants",
  "Shorts",
  "Linen Layers",
  "Swimwear & Beachwear",
  "Shirts & Blouses",
  "Basics",
  "Skirts",
  "Heels",
  "Shoes",
  "Boots",
  "Sneakers",
  "Cardigans & Sweaters",

  "Blazers & Vests",
  "Jackets & Coats",
  "Outerwear",
  "Jumpsuits & Overalls",
  "Lingerie",
  "Loungewear",
  "Nightwear",
  "Socks & Tights",
  "Maternity Wear",
  "Hoodies & Sweatshirts",
  "Accessories",
  "Bags",
  "Headwear",
  "Jewelry",
  "Sunglasses",
  "Activewear",
  "Makeup",
  "Other",
];

const List<String> wardrobeColors = [
  "Black",
  "White",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Pink",
  "Purple",
  "Orange",
  "Gray",
  "Brown",
  "Beige",
  "Navy",
  "Teal",
  "Gold",
  "Silver",
  "Multicolor",
  "Other",
];

// Not used in the current implementation
// const List<String> wardrobeBrands = [
//   "Zara",
//   "H&M",
//   "Mango",
//   "Bershka",
//   "Pull & Bear",
//   "Stradivarius",
//   "Arket",
//   "Massimo Dutti",
//   "Uniqlo",
//   "Other Stories",
//   "Lindex"
//   "Åhléns",
//   "COS",
//   "Weekday",
//   "Monki",
//   "Boohoo",
//   "Urban Outfitters",
//   "ASOS",
//   "Shein",
//   "Cider",
//   "Forever 21",
//   "Temu",
//   "PrettyLittleThing",
//   "Indiska",
//   "Kappahl",
//   "Samsoe & Samsoe",
//   "Filippa K",
//   "Acne Studios",
//   "Ganni",
//   "Vero Moda",
//   "Only",
//   "Jack & Jones",
//   "Selected",
//   "Boozt",
//   "Nelly",
//   "Zalando",
//   "Vagabond",
//   "Dr. Martens",
//   "Converse",
//   "Vans",
//   "New Balance",
//   "Reebok",
//   "Timberland",
//   "Clarks",
//   "Skechers",
//   "Tamaris",
//   "ECCO",
//   "Nike",
//   "Adidas",
//   "Puma",
//   "Reebok",
//   "Levi's",
//   "Calvin Klein",
//   "Tommy Hilfiger",
//   "Gucci",
//   "Prada",
//   "Chanel",
//   "Louis Vuitton",
//   "Burberry",
//   "Versace",
//   "Dolce & Gabbana",
//   "Other"
// ];
