// lib/constants/wardrobe_constants.dart
const List<String> wardrobeCategories = [
  "Dresses",
  "Tops & T-Shirts",
  "Polos",
  "Jeans",
  "Pants",
  "Shorts",
  "Linen Layers",
  "Swimwear & Beachwear",
  "Shirts & Blouses",
  "Basics",
  "Skirts",
  "Heels",
  "Shoes",
  "Boots",
  "Sneakers",
  "Cardigans & Sweaters",

  "Blazers & Vests",
  "Jackets & Coats",
  "Outerwear",
  "Jumpsuits & Overalls",
  "Lingerie",
  "Loungewear",
  "Nightwear",
  "Socks & Tights",
  "Maternity Wear",
  "Hoodies & Sweatshirts",
  "Accessories",
  "Bags",
  "Headwear",
  "Jewelry",
  "Sunglasses",
  "Activewear",
  "Makeup",
  "Other",
];

const List<String> wardrobeColors = [
  "Black",
  "White",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Pink",
  "Purple",
  "Orange",
  "Gray",
  "Brown",
  "Beige",
  "Navy",
  "Teal",
  "Gold",
  "Silver",
  "Multicolor",
  "Other",
];

// Not used in the current implementation
const List<String> wardrobeBrands = [
  "Zara",
  "H&M",
  "Mango",
  "Bershka",
  "Pull & Bear",
  "Stradivarius",
  "Carin Wester",
  "Arket",
  "Massimo Dutti",
  "Uniqlo",
  "& Other Stories",
  "Lindex",
  "Åhléns",
  "COS",
  "Weekday",
  "Monki",
  "Boohoo",
  "Urban Outfitters",
  "ASOS",
  "Shein",
  "Cider",
  "Forever 21",
  "Temu",
  "PrettyLittleThing",
  "Indiska",
  "Kappahl",
  "Samsoe & Samsoe",
  "Filippa K",
  "Acne Studios",
  "Ganni",
  "Vero Moda",
  "Only",
  "Jack & Jones",
  "Selected",
  "Boozt",
  "Nelly",
  "Zalando",
  "Vagabond",
  "Dr. Martens",
  "Converse",
  "Vans",
  "New Balance",
  "Reebok",
  "Timberland",
  "Clarks",
  "Skechers",
  "Tamaris",
  "ECCO",
  "Nike",
  "Adidas",
  "Puma",
  "Levi's",
  "Calvin Klein",
  "Tommy Hilfiger",
  "Gucci",
  "Prada",
  "Chanel",
  "Louis Vuitton",
  "Burberry",
  "Versace",
  "Dolce & Gabbana",
  "Balenciaga",
  "Saint Laurent",
  "Celine",
  "Dior",
  "Fendi",
  "Givenchy",
  "Off-White",
  "Balmain",
  "Moncler",
  "Stone Island",
  "Superdry",
  "River Island",
  "Topshop",
  "Topman",
  "Primark",
  "Hollister",
  "Abercrombie & Fitch",
  "Superdry",
  "Under Armour",
  "The North Face",
  "Patagonia",
  "Arc'teryx",
  "Asics",
  "Salomon",
  "Merrell",
  "Birkenstock",
  "Crocs",
  "UGG",
  "Other",
];

const List<String> wardrobeSizes = [
  // International clothing sizes
  'XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL',
  // Pants (EU sizes)
  'EU28', 'EU29', 'EU30', 'EU31', 'EU32', 'EU33', 'EU34', 'EU35',
  'EU36', 'EU37', 'EU38', 'EU39', 'EU40', 'EU41', 'EU42', 'EU43',
  'EU44', 'EU45', 'EU46',
  // Bras (simplified range)
  '70K', '70L', '70M', '75A', '75B', '75C', '75D', '75E', '75F',
  // Shoes (EU sizes)
  'EU33', 'EU34', 'EU35', 'EU36', 'EU37', 'EU38', 'EU39', 'EU40',
  'EU41', 'EU42', 'EU43', 'EU44', 'EU45', 'EU46', 'EU47', 'EU48',
  // Other
  'Other', 'Unknown',
];
